# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cfeb4f7139c1ff0bda052134bbda6c6d8bd603ec098993c167b15e6fccdc7bddc3e1ad8da11dea13d76fe016685f4633c3188c8bda122f43ef6888d52953853

test:
  secret_key_base: d624ee148a7bb2d96a60a2ce71aca1fe5767ad23a28919781e2bb6ca2fc831aa9ca4b72d5ed17cf167a2b72e70cd9c89bbce09cdd717d85a44e3ecc5da9ce814

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
